const PRODUCT_DETAIL_BY_ID_REQUEST = "PRODUCT_DETAIL_BY_ID_REQUEST"

const PRODUCT_DETAIL_BY_ID_SUCCESS = "PRODUCT_DETAIL_BY_ID_SUCCESS"

const PRODUCT_DETAIL_BY_ID_FAIL = "PRODUCT_DETAIL_BY_ID_FAIL"

export {PRODUCT_DETAIL_BY_ID_SUCCESS, PRODUCT_DETAIL_BY_ID_FAIL, PRODUCT_DETAIL_BY_ID_REQUEST}
