const PRODUCT_DETAIL_BY_ID_REQUEST = "PRODUCT_DETAIL_BY_ID_REQUEST"

const PRODUCT_DETAIL_BY_ID_SUCCESS = "PRODUCT_DETAIL_BY_ID_SUCCESS"

const PRODUCT_DETAIL_BY_ID_FAIL = "PRODUCT_DETAIL_BY_ID_FAIL"

const PRODUCTS_GET_ALL_REQUEST = "PRODUCTS_GET_ALL_REQUEST"

const PRODUCTS_GET_ALL_SUCCESS = "PRODUCTS_GET_ALL_SUCCESS"

const PRODUCT_GET_ALL_FAIL = "PRODUCTS_GET_ALL_FAIL"

const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST"

const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS"

const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL"

export {PRODUCT_DETAIL_BY_ID_SUCCESS, PRODUCT_DETAIL_BY_ID_FAIL, PRODUCT_DETAIL_BY_ID_REQUEST, PRODUCTS_GET_ALL_SUCCESS, PRODUCT_GET_ALL_FAIL, PRODUCTS_GET_ALL_REQUEST, PRODUCT_CREATE_SUCCESS, PRODUCT_CREATE_REQUEST, PRODUCT_CREATE_FAIL}
